#1. Set platform folder.

if(WIN32)
    set(PLATFORM_FOLDER win32)
elseif(APPLE)
    set(PLATFORM_FOLDER ios)
elseif(ANDROID)
    set(PLATFORM_FOLDER android)
else()
    set(PLATFORM_FOLDER linux)
endif()

#2. Set Define Marco
ADD_DEFINITIONS(-DUNICODE -D_UNICODE)
SET(CMAKE_CXX_FLAGS_DEBUG -D_DEBUG)
SET(CMAKE_CXX_FLAGS_RELEASE -DNDEBUG)
if(WIN32)
  ADD_DEFINITIONS (-DWIN32 -D_WINDOWS)  
  if(MSVC)
  	ADD_DEFINITIONS (-D_CRT_SECURE_NO_WARNINGS -D_CRT_NON_CONFORMING_SWPRINTFS -D_SCL_SECURE_NO_WARNINGS -wd4100 -wd4127)
  else(MSVC)  
  endif(MSVC)
elseif(APPLE)
elseif(ANDROID)
else()#Linux
    ADD_DEFINITIONS(-DLINUX)
endif()
