#1. Set platform folder.

if(WIN32)
    set(PLATFORM_FOLDER win32)
elseif(APPLE)
    set(PLATFORM_FOLDER ios)
else()
    set(PLATFORM_FOLDER android)
endif()

SET(CMAKE_CXX_FLAGS "-std=c++0x")

#2. Set Define Marco
if (WIN32)
else()
endif()

if(WIN32)
  ADD_DEFINITIONS (-DWIN32 -D_WINDOWS)  
  if(MSVC)
    SET(CMAKE_CXX_FLAGS_DEBUG -D_DEBUG " /MDd /Od /ZI")
    SET(CMAKE_CXX_FLAGS_RELEASE -DNDEBUG " /MD /O2")
  	ADD_DEFINITIONS (-D_CRT_SECURE_NO_WARNINGS -D_CRT_NON_CONFORMING_SWPRINTFS -D_SCL_SECURE_NO_WARNINGS -wd4100 -wd4127)
  else(MSVC)  
  endif(MSVC)
elseif(APPLE)
elseif(ANDROID)

macro(filter_platform_files FILE_LIST PLATFORM_DIR_NAME CURR_PLATFORM)
	set(PLATFORM_NAMES win32 ios android linux)
	foreach(FILE ${${FILE_LIST}})
		string(REGEX MATCH ${PLATFORM_DIR_NAME} MATCH_RESULT ${FILE})
		if(MATCH_RESULT)
			foreach(PLATFORM_NAME ${PLATFORM_NAMES})
				if(NOT ${CURR_PLATFORM} STREQUAL ${PLATFORM_NAME})
					string(REGEX MATCH ${PLATFORM_NAME} MATCH_RESULT1 ${FILE})
					if(MATCH_RESULT1)
						list(REMOVE_ITEM ${FILE_LIST} ${FILE})
					endif()
				endif()
			endforeach()
		endif()
	endforeach()
endmacro()
endif()
