#ifndef EVENT_EVENT_TYPE_H__INCLUDE
#define EVENT_EVENT_TYPE_H__INCLUDE

enum EventType
{
    EVENT_MOUSE = 1 << 24,
    EVENT_MOUSE_PRESSED,
    EVENT_MOUSE_RELEASED,
    EVENT_MOUSE_MOVED,
    EVENT_MOUSE_SCROLLED,

    EVENT_KEYBOARD = 2 << 24,
    EVENT_KEY_PRESSED,
    EVENT_KEY_RELEASED,
    EVENT_KEY_REPEATED,
    EVENT_CHAR,

    EVENT_GUI = 3 << 24,
    EVENT_ANIMATION = 4 << 24,
};

#endif