#ifndef EVENT_EVENT_TYPE_H__INCLUDE
#define EVENT_EVENT_TYPE_H__INCLUDE

enum EventType
{
    EVENT_MOUSE = 1 << 24,
    EVENT_MOUSE_PRESS,
    EVENT_MOUSE_RELEASE,
    EVENT_MOUSE_MOVE,
    EVENT_MOUSE_SCROLL,

    EVENT_KEYBOARD = 2 << 24,
    EVENT_KEY_PRESS,
    EVENT_KEY_RELEASE,
    EVENT_KEY_REPEAT,
    EVENT_CHAR,

    EVENT_GUI = 3 << 24,
};

#endif