#ifndef BEATS_PLATFORM_BEATSPLATFORM_H__INCLUDE
#define BEATS_PLATFORM_BEATSPLATFORM_H__INCLUDE

#define PLATFORM_UNKNOWN 0
#define PLATFORM_WIN32  1
#define PLATFORM_IOS    2
#define PLATFORM_ANDROID 3

#define BEATS_PLATFORM PLATFORM_UNKNOWN

#endif