# Generated by VisualGDB

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE    := Components-static
#VisualGDBAndroid: AutoUpdateSourcesInNextLine
LOCAL_SRC_FILES := ../../../../Components/Component/ComponentBase.cpp ../../../../Components/Component/ComponentGraphic.cpp ../../../../Components/Component/ComponentInstance.cpp ../../../../Components/Component/ComponentInstanceManager.cpp ../../../../Components/Component/ComponentManagerBase.cpp ../../../../Components/Component/ComponentProject.cpp ../../../../Components/Component/ComponentProjectData.cpp ../../../../Components/Component/ComponentProxy.cpp ../../../../Components/Component/ComponentProxyManager.cpp ../../../../Components/DependencyDescription.cpp ../../../../Components/DependencyDescriptionLine.cpp ../../../../Components/Property/PropertyDescriptionBase.cpp ../../../../Components/stdafx.cpp
LOCAL_C_INCLUDES := C:\Project\Beats_GitHub\Components C:\Project\Beats_GitHub\Platform C:\Project\Beats_GitHub\Platform\Android C:/Project/Beats_GitHub/Utility C:/Project/Beats_GitHub
LOCAL_SHARED_LIBRARIES := 
LOCAL_LDLIBS := 
LOCAL_CFLAGS := 
LOCAL_CPPFLAGS := 
LOCAL_LDFLAGS := 
include $(BUILD_STATIC_LIBRARY)
